# Generated by Django 3.2.15 on 2023-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('stock', models.BooleanField()),
            ],
        ),
    ]
